name: cassini-deployment

on:
  push:
    branches: ['main', 'automate-deploy']
  workflow_dispatch:

env:
  HOST: cassini.cs.kent.edu
  USER: deltabeatz
  TARGET: deltabeatz@cassini.cs.kent.edu
  PUBLICKEY: ${{ secrets.ID_RSA }}
  PASSWORD: ${{ secrets.PASSWORD }}
  RUN: ssh -o LogLevel=ERROR -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no deltabeatz@cassini.cs.kent.edu
  COPY: scp -o LogLevel=ERROR -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no 

jobs:
  deploy_to_server:
    runs-on: ubuntu-latest
    steps:
      - name: Install ssh key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.ID_RSA }}
          name: id_rsa
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
      - name: Get repo code
        uses: actions/checkout@v2
        with:
          repository: src-img/deltaTeam
      - name: Copy code to server
        run: |
          $RUN 'mkdir -p /home/web'
          $RUN 'rm -r /home/web/*'
          $COPY -r database $TARGET:/home/web/database
          $COPY -r static $TARGET:/home/web/static
          $COPY -r templates $TARGET:/home/web/templates
          $COPY main.py $TARGET:/home/web
          $COPY recordUserInput.py $TARGET:/home/web
          $RUN 'ls -1a /home/web'